server:
  port: 0

debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.hanghae.stockservice: debug
    org.springframework.web.servlet: debug
    org.springframework.transaction.interceptor: trace
    org.hibernate.type.descriptor.sql: trace

spring:
  application:
    name: stock-service
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100


  h2.console.enabled: false
  sql.init.mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DEFAULT_ZONE_URL}

